### PR TITLE
Graphs

### PR DESCRIPTION
**Pull request by probablytom**
More graphs and tooltips too.

### CODE REVIEW

**Comment by probablytom** [comment]
(Just in case it wasn't already obvious, this isn't worth merging yet, we should probably add more graphs first!)

**Comment by darrenburns** [comment]
Did you rewrite the project?
> Files changed: 895

**Comment by probablytom** [comment]
I can't see why I would have, but I don't remember writing 47,700 lines of code lately. I'll go back through my commits and see what's up...

**Comment by probablytom** [comment]
It's the latest commit. Any work will be easy to redo, so reverting's fine by me

**Comment by darrenburns** [comment]
Ok, I've reverted that commit for you @probablytom

**Comment by probablytom** [comment]
Thanks! Sorry -- I'd have done it myself, but I wasn't at home.

**Comment by probablytom** [comment]
Ah -- I'd ran collectstatic when I was having troubles with static files, and it had created a whole load of static files in staticfiles/. I think that was why the commit was so big. My bad!

**Comment by probablytom** [comment]
This has another visualisation now, and the tooltips are working locally for all three graphs. Now might be a good time to merge, while it's stable!

**Pull request merged**
